name = "norm-forms"
version = "0.1.0"
defaultTargets = ["NormForms", "NormFormsTests"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "83abb3e776bdefcbc447a1e44d0debe4010039e5"

[[require]]
name = "multivariate-polynomials"
git = "https://github.com/FormalFrontier/multivariate-polynomials.git"
rev = "ec4906268f2a65a54e320ce9f3f44562e9d78c1e"

[[lean_lib]]
name = "NormForms"

[[lean_lib]]
name = "NormFormsTests"
