name = "norm-forms"
version = "0.1.0"
defaultTargets = ["NormForms", "NormFormsTests"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "83abb3e776bdefcbc447a1e44d0debe4010039e5"

[[require]]
name = "multivariate-polynomials"
git = "https://github.com/FormalFrontier/multivariate-polynomials.git"
rev = "6a04276766ad82d60702b24deb9a559a30a80007"

[[require]]
name = "algebraic-groups"
git = "https://github.com/FormalFrontier/algebraic-groups.git"
rev = "6c7f4a5a38881573fd2bb735fc3dab1de53b83bf"

[[require]]
name = "sequence-growth"
git = "https://github.com/FormalFrontier/sequence-growth.git"
rev = "c5c4dbfafc3a6b3fdc8c6ab9f3d336ae893d4f79"

[[lean_lib]]
name = "NormForms"

[[lean_lib]]
name = "NormFormsTests"
